### ISSUE TITLE
0.17.4-beta breaks lntop

### ISSUE THREAD

**Issue by dskvr** [edouardparis/lntop#111]
lnd: `0.17.4-beta`

error:

```
panic: send on closed channel

goroutine 29 [running]:
github.com/edouardparis/lntop/network/backend/lnd.Backend.SubscribeRoutingEvents({0x400040e6a0?, {0xdddfa0?, 0x400012dcc0?}, 0x400049c8d0?}, {0xddc6a8, 0x400048d180}, 0x0?)
        /home/admin/lntop/network/backend/lnd/lnd.go:254 +0x128
github.com/edouardparis/lntop/pubsub.(*PubSub).routingUpdates.func2()
        /home/admin/lntop/pubsub/pubsub.go:105 +0x44
created by github.com/edouardparis/lntop/pubsub.(*PubSub).routingUpdates
        /home/admin/lntop/pubsub/pubsub.go:104 +0x15c
        
panic: send on closed channel

goroutine 35 [running]:
github.com/edouardparis/lntop/network/backend/lnd.Backend.SubscribeGraphEvents({0x400040e6a0?, {0xdddfa0?, 0x400012dcc0?}, 0x400049c8d0?}, {0xddc6a8, 0x400048d200}, 0x0?)
        /home/admin/lntop/network/backend/lnd/lnd.go:221 +0x1cc
github.com/edouardparis/lntop/pubsub.(*PubSub).graphUpdates.func2()
        /home/admin/lntop/pubsub/pubsub.go:134 +0x44
created by github.com/edouardparis/lntop/pubsub.(*PubSub).graphUpdates
        /home/admin/lntop/pubsub/pubsub.go:133 +0x15c
```

**Comment by hieblmi** [comment]
Can you try running the branch in this commit which uses `v0.18.0-beta.rc1`?
