### ISSUE TITLE
Crash with wallet-balance

### ISSUE THREAD

**Issue by C-Otto** [edouardparis/lntop#4]
I compiled on another node and just copied the binary.

```
$ lntop wallet-balance
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72da74]

goroutine 1 [running]:
go.uber.org/zap.(*Logger).clone(...)
	/home/cotto/lntop/vendor/go.uber.org/zap/logger.go:252
go.uber.org/zap.(*Logger).With(0x0, 0xc0000a4c40, 0x1, 0x1, 0x0)
	/home/cotto/lntop/vendor/go.uber.org/zap/logger.go:163 +0x44
github.com/edouardparis/lntop/network.New(0xc0001ceca0, 0xbdbe80, 0x0, 0x0, 0xbdbe80, 0x0)
	/home/cotto/lntop/network/network.go:23 +0x219
github.com/edouardparis/lntop/cli.getNetworkFromConfig(0xc00019b5c0, 0xc0001cdd70, 0x5708a2, 0xc00019b5c0)
	/home/cotto/lntop/cli/cli.go:108 +0xdb
github.com/edouardparis/lntop/cli.walletBalance(0xc00019b5c0, 0xb24d97, 0xe)
	/home/cotto/lntop/cli/cli.go:112 +0x2f
gopkg.in/urfave/cli%2ev2.(*Command).Run(0xc0001b8480, 0xc00019b560, 0x0, 0x0)
	/home/cotto/lntop/vendor/gopkg.in/urfave/cli.v2/command.go:167 +0x709
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000001c80, 0xc00000c060, 0x2, 0x2, 0x0, 0x0)
	/home/cotto/lntop/vendor/gopkg.in/urfave/cli.v2/app.go:261 +0x675
main.main()
	/home/cotto/lntop/cmd/lntop/main.go:11 +0x4f
```

**Comment by edouardparis** [comment]
Thank you for the issue, I removed this command which was deprecated.
Please, send me a link to a tip page, so i can send you some sats.

**Comment by C-Otto** [comment]
Thanks :)

lightning:lnbc1pwtrd9ppp5fswc3deeuzkr6plf0hvavw7yp86r2uaz7puuv5kl62r7x409qsfsdqqxqruyqrzjqf7wq4fcqdyd0qfd9tnhg4cpe8unuuxp4h4jv4ls20u3ma8jss78zz9j2gqqfusqqqqqqqlgqqqqqeqqjqrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glc7z9n4yqqdrqqqqqqqqlgqqqqqeqqjqwgja0yzjsxdha7dk4yq4rduzvgkuywmh3ps4p6q0mmm8z9gaydnka0sfr7j4n8w265ym8dssu6f5ndvmlaskd04wnuw3vlz9z4dz49spd7qgxn

**Comment by edouardparis** [comment]
sorry I tried several time https://keybase.pub/edouardparis/Screenshot_20190413-124938.jpg

**Comment by C-Otto** [comment]
I also use Eclair on my phone, and it seems I have to leave the app open. Another lesson learned :)
