### ISSUE TITLE
Crash when trying to run the compiled binary

### ISSUE THREAD

**Issue by reynico** [edouardparis/lntop#9]
Hi!
Got this issue:
```
~/go/bin$ ./lntop
panic: runtime error: integer divide by zero

goroutine 7 [running]:
github.com/edouardparis/lntop/ui/views.gaugeTotal(0x0, 0x10cbc78, 0x0, 0x0, 0x11, 0x4b)
        /home/ubuntu/lntop/ui/views/summary.go:89 +0x30a
github.com/edouardparis/lntop/ui/views.(*Summary).display(0xc0002488a0)
        /home/ubuntu/lntop/ui/views/summary.go:71 +0xbd0
github.com/edouardparis/lntop/ui/views.(*Summary).Set(0xc0002488a0, 0xc000294240, 0x0, 0x1, 0xa9, 0x6, 0x0, 0x0)
        /home/ubuntu/lntop/ui/views/summary.go:49 +0x226
github.com/edouardparis/lntop/ui/views.(*Views).Layout(0xc000246600, 0xc000294240, 0xa9, 0x12, 0xa90012, 0xc0002f3c10)
        /home/ubuntu/lntop/ui/views/views.go:53 +0xb6
github.com/edouardparis/lntop/ui.(*controller).layout(0xc000260b20, 0xc000294240, 0x12, 0xc0002f3c78)
        /home/ubuntu/lntop/ui/controller.go:23 +0x4b
github.com/edouardparis/lntop/ui.(*controller).layout-fm(0xc000294240, 0x0, 0x0)
        /home/ubuntu/lntop/ui/ui.go:26 +0x34
github.com/jroimartin/gocui.ManagerFunc.Layout(0xc0003c8540, 0xc000294240, 0x0, 0xc0002f3ce0)
        /home/ubuntu/lntop/vendor/github.com/jroimartin/gocui/gui.go:329 +0x30
github.com/jroimartin/gocui.(*Gui).flush(0xc000294240, 0x2, 0xc000294240)
        /home/ubuntu/lntop/vendor/github.com/jroimartin/gocui/gui.go:435 +0xce
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc000294240, 0xb4b4a0, 0xc000260b20)
        /home/ubuntu/lntop/vendor/github.com/jroimartin/gocui/gui.go:367 +0xbd
github.com/edouardparis/lntop/ui.Run(0xbdca00, 0xc000036098, 0xc00023ec60, 0xc000084780, 0x0, 0x0)
        /home/ubuntu/lntop/ui/ui.go:35 +0x1b9
github.com/edouardparis/lntop/cli.run.func1(0xbdca00, 0xc000036098, 0xc00023ec60, 0xc000084780, 0xc000173e30)
        /home/ubuntu/lntop/cli/cli.go:64 +0x6a
created by github.com/edouardparis/lntop/cli.run
        /home/ubuntu/lntop/cli/cli.go:63 +0x14e
```

Machine details:
```
~/go/bin$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
~/go/bin$ uname -a
Linux ip-10-0-11-213 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

Compiled with:
```
cd lntop && export GO111MODULE=on && go install -mod=vendor ./...
```

I did `export LND_HOME=~/.lnd` before running `lntop`. I got my `~/.lntop/config.toml` properly setup

```
[logger]
type = "development"
dest = "/home/ubuntu/.lntop/lntop.log"

[network]
name = "lnd"
type = "lnd"
address = "//127.0.0.1:10009"
cert = "/home/ubuntu/.lnd/tls.cert"
macaroon = "/home/ubuntu/.lnd/admin.macaroon"
macaroon_timeout = 60
max_msg_recv_size = 52428800
conn_timeout = 1000000
pool_capacity = 3
```

Is there any way to debug this? Thanks!

**Comment by edouardparis** [comment]
Hello, thank you for this issue. Your node had no channel and I forget to check capacity not null.
Please, pull from master and rebuild it with `go install -mod=vendor`

**Comment by reynico** [comment]
Works great, thanks!
