### ISSUE TITLE
lntop won't start

### ISSUE THREAD

**Issue by caotic112** [edouardparis/lntop#95]
-Debian 11 , lntop v0.3.1

-After the recent lnd bug I can't start lntop anymore:

panic: send on closed channel

goroutine 23 [running]:
github.com/edouardparis/lntop/network/backend/lnd.Backend.SubscribeGraphEvents({0xc0000fc620?, {0x1208b10?, 0xc000097a90?}, 0xc0003441e0?}, {0x1207488, 0xc00033ed80}, 0x0?)
        /home/lnd/lntop/network/backend/lnd/lnd.go:219 +0x27c
github.com/edouardparis/lntop/pubsub.(*PubSub).graphUpdates.func2()
        /home/lnd/lntop/pubsub/pubsub.go:134 +0x4f
created by github.com/edouardparis/lntop/pubsub.(*PubSub).graphUpdates
        /home/lnd/lntop/pubsub/pubsub.go:133 +0x158

-Somtimes it' just a black screen for a moment and then back to the shell with no output.

**Comment by edouardparis** [comment]
Thanks for reporting the issue, We will try to release a new binary with a fix ASAP

**Comment by caotic112** [comment]
Not sure but I think that a pending channel during the bug is the cause. 
The channel it's now up on my side but I can't get info about it:
[lncli] rpc error: code = Unknown desc = edge not found
The other side it's still offline I'm waiting to see if lntop fix itself when my peer comes back online.

**Comment by rkfg** [comment]
It's probably [this lnd issue](https://github.com/lightningnetwork/lnd/issues/6882) then. Have you updated lnd to 0.15.2? There was another nasty bug recently so this update is required I think.

**Comment by caotic112** [comment]
Yes I'm already on 0.15.2, I have done several restart but they dind't help.
I'm still waiting for the pending channel peer to come back up .

**Comment by rkfg** [comment]
As a temporary measure you can comment out this line: https://github.com/edouardparis/lntop/blob/dcefd63a86f2ee6d3484edbe3b22f38e7e3efd04/ui/models/models.go#L70
(change it to `// return err`) and recompile `lntop`. If the problem is a missing policy it should help.

**Comment by caotic112** [comment]
yes!!!it works again!

**Comment by rkfg** [comment]
I think it should be patched, inability to query a single channel shouldn't be a show stopper. Just logging the error and continuing should be okay, at worst it'd be a stale channel showing outdated information.
